// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ElectricVehicleM.Repositories.QuangNM.Models;

public partial class CustomersBaoTdq
{
    public int CustomerBaoTdqid { get; set; }

    public string FullName { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public DateTime? Dob { get; set; }

    public bool? IsVip { get; set; }

    public decimal? TotalSpent { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? AppointmentBaoTdqid { get; set; }

    public virtual TestDriveAppointmentsBaoTdq AppointmentBaoTdq { get; set; }
}