// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ElectricVehicleM.Repositories.QuangNM.Models;

public partial class DealersMinhNq
{
    public int DealerMinhNqid { get; set; }

    public string DealerName { get; set; }

    public string Location { get; set; }

    public string ContactPerson { get; set; }

    public string PhoneNumber { get; set; }

    public DateTime? ContractDate { get; set; }

    public bool? IsActive { get; set; }

    public decimal? SalesTarget { get; set; }

    public decimal? DebtAmount { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? ContractMinhNqid { get; set; }

    public virtual DealerContractsMinhNq ContractMinhNq { get; set; }
}