// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ElectricVehicleM.Repositories.QuangNM.Models;

public partial class DealerContractsMinhNq
{
    public int ContractMinhNqid { get; set; }

    public DateTime? ContractDate { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public bool? IsSigned { get; set; }

    public virtual ICollection<DealersMinhNq> DealersMinhNqs { get; set; } = new List<DealersMinhNq>();
}