// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ElectricVehicleM.Repositories.QuangNM.Models;

public partial class OrderItemsMinhPhn
{
    public int OrderItemMinhPhnid { get; set; }

    public string ItemName { get; set; }

    public int? Quantity { get; set; }

    public bool? IsDelivered { get; set; }

    public virtual ICollection<SalesOrdersMinhPhn> SalesOrdersMinhPhns { get; set; } = new List<SalesOrdersMinhPhn>();
}