// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ElectricVehicleM.Repositories.QuangNM.Models;

public partial class PromotionUsageQuangNm
{
    [Key]
    public int UsageQuangNmid { get; set; }

    public string CustomerName { get; set; }

    public DateTime? UsedDate { get; set; }

    public bool? IsValid { get; set; }

    public virtual ICollection<PromotionsQuangNm> PromotionsQuangNms { get; set; } = new List<PromotionsQuangNm>();
}