// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ElectricVehicleM.Repositories.QuangNM.Models;

public partial class PromotionsQuangNm
{
    [Key]
    public int PromotionQuangNmid { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public decimal? DiscountRate { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public bool? IsActive { get; set; }

    public string ApplicableModel { get; set; }

    public int? MaxUsage { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? UsageQuangNmid { get; set; }

    public virtual PromotionUsageQuangNm UsageQuangNm { get; set; }
}