// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ElectricVehicleM.Repositories.QuangNM.Models;

public partial class ReportsPhucLt
{
    public int ReportPhucLtid { get; set; }

    public string ReportName { get; set; }

    public string ReportType { get; set; }

    public string GeneratedBy { get; set; }

    public DateTime? GeneratedDate { get; set; }

    public bool? IsArchived { get; set; }

    public decimal? SalesFigure { get; set; }

    public int? InventoryLevel { get; set; }

    public string Notes { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? DetailPhucLtid { get; set; }

    public virtual ReportDetailsPhucLt DetailPhucLt { get; set; }
}