// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ElectricVehicleM.Repositories.QuangNM.Models;

public partial class ReportDetailsPhucLt
{
    public int DetailPhucLtid { get; set; }

    public string SectionName { get; set; }

    public string Value { get; set; }

    public bool? IsVerified { get; set; }

    public virtual ICollection<ReportsPhucLt> ReportsPhucLts { get; set; } = new List<ReportsPhucLt>();
}