// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ElectricVehicleM.Repositories.QuangNM.Models;

public partial class SalesOrdersMinhPhn
{
    public int OrderMinhPhnid { get; set; }

    public string OrderCode { get; set; }

    public string BuyerName { get; set; }

    public string VehicleModel { get; set; }

    public DateTime? OrderDate { get; set; }

    public decimal? TotalAmount { get; set; }

    public string PaymentType { get; set; }

    public bool? IsPaid { get; set; }

    public DateTime? DeliveryDate { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? OrderItemMinhPhnid { get; set; }

    public virtual OrderItemsMinhPhn OrderItemMinhPhn { get; set; }
}