// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ElectricVehicleM.Repositories.QuangNM.Models;

public partial class TestDriveAppointmentsBaoTdq
{
    public int AppointmentBaoTdqid { get; set; }

    public string VehicleModel { get; set; }

    public DateTime? AppointmentDate { get; set; }

    public bool? IsCompleted { get; set; }

    public virtual ICollection<CustomersBaoTdq> CustomersBaoTdqs { get; set; } = new List<CustomersBaoTdq>();
}