// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ElectricVehicleM.Repositories.QuangNM.Models;

public partial class VehicleFeaturesDatPht
{
    public int FeatureDatPhtid { get; set; }

    public string FeatureName { get; set; }

    public string Description { get; set; }

    public bool? IsStandard { get; set; }

    public virtual ICollection<VehiclesDatPht> VehiclesDatPhts { get; set; } = new List<VehiclesDatPht>();
}