// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ElectricVehicleM.Repositories.QuangNM.Models;

public partial class VehiclesDatPht
{
    public int VehicleDatPhtid { get; set; }

    public string ModelName { get; set; }

    public string Version { get; set; }

    public string Color { get; set; }

    public decimal? Price { get; set; }

    public int? StockQuantity { get; set; }

    public DateTime? ReleaseDate { get; set; }

    public bool? IsAvailable { get; set; }

    public int? WarrantyYears { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? FeatureDatPhtid { get; set; }

    public virtual VehicleFeaturesDatPht FeatureDatPht { get; set; }
}