//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PromotionsQuangNm", Namespace="http://schemas.datacontract.org/2004/07/ElectricVehicleM.SoapService.QuangNM.Soap" +
        "Models")]
    public partial class PromotionsQuangNm : object
    {
        
        private string ApplicableModelField;
        
        private System.Nullable<System.DateTime> CreatedAtField;
        
        private string DescriptionField;
        
        private System.Nullable<decimal> DiscountRateField;
        
        private System.Nullable<System.DateTime> EndDateField;
        
        private System.Nullable<bool> IsActiveField;
        
        private System.Nullable<int> MaxUsageField;
        
        private int PromotionQuangNmidField;
        
        private System.Nullable<System.DateTime> StartDateField;
        
        private string TitleField;
        
        private ServiceReference1.PromotionUsageQuangNm UsageQuangNmField;
        
        private System.Nullable<int> UsageQuangNmidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicableModel
        {
            get
            {
                return this.ApplicableModelField;
            }
            set
            {
                this.ApplicableModelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DiscountRate
        {
            get
            {
                return this.DiscountRateField;
            }
            set
            {
                this.DiscountRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaxUsage
        {
            get
            {
                return this.MaxUsageField;
            }
            set
            {
                this.MaxUsageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PromotionQuangNmid
        {
            get
            {
                return this.PromotionQuangNmidField;
            }
            set
            {
                this.PromotionQuangNmidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.PromotionUsageQuangNm UsageQuangNm
        {
            get
            {
                return this.UsageQuangNmField;
            }
            set
            {
                this.UsageQuangNmField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UsageQuangNmid
        {
            get
            {
                return this.UsageQuangNmidField;
            }
            set
            {
                this.UsageQuangNmidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PromotionUsageQuangNm", Namespace="http://schemas.datacontract.org/2004/07/ElectricVehicleM.SoapService.QuangNM.Soap" +
        "Models")]
    public partial class PromotionUsageQuangNm : object
    {
        
        private string CustomerNameField;
        
        private System.Nullable<bool> IsValidField;
        
        private ServiceReference1.PromotionsQuangNm[] PromotionsQuangNmsField;
        
        private int UsageQuangNmidField;
        
        private System.Nullable<System.DateTime> UsedDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName
        {
            get
            {
                return this.CustomerNameField;
            }
            set
            {
                this.CustomerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsValid
        {
            get
            {
                return this.IsValidField;
            }
            set
            {
                this.IsValidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.PromotionsQuangNm[] PromotionsQuangNms
        {
            get
            {
                return this.PromotionsQuangNmsField;
            }
            set
            {
                this.PromotionsQuangNmsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsageQuangNmid
        {
            get
            {
                return this.UsageQuangNmidField;
            }
            set
            {
                this.UsageQuangNmidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UsedDate
        {
            get
            {
                return this.UsedDateField;
            }
            set
            {
                this.UsedDateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPromotionsQuangNmSoapService")]
    public interface IPromotionsQuangNmSoapService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionsQuangNmSoapService/GetAll", ReplyAction="http://tempuri.org/IPromotionsQuangNmSoapService/GetAllResponse")]
        System.Threading.Tasks.Task<ServiceReference1.PromotionsQuangNm[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionsQuangNmSoapService/GetById", ReplyAction="http://tempuri.org/IPromotionsQuangNmSoapService/GetByIdResponse")]
        System.Threading.Tasks.Task<ServiceReference1.PromotionsQuangNm> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionsQuangNmSoapService/Create", ReplyAction="http://tempuri.org/IPromotionsQuangNmSoapService/CreateResponse")]
        System.Threading.Tasks.Task<int> CreateAsync(ServiceReference1.PromotionsQuangNm promotion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionsQuangNmSoapService/Update", ReplyAction="http://tempuri.org/IPromotionsQuangNmSoapService/UpdateResponse")]
        System.Threading.Tasks.Task<int> UpdateAsync(ServiceReference1.PromotionsQuangNm promotion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionsQuangNmSoapService/Delete", ReplyAction="http://tempuri.org/IPromotionsQuangNmSoapService/DeleteResponse")]
        System.Threading.Tasks.Task<int> DeleteAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IPromotionsQuangNmSoapServiceChannel : ServiceReference1.IPromotionsQuangNmSoapService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class PromotionsQuangNmSoapServiceClient : System.ServiceModel.ClientBase<ServiceReference1.IPromotionsQuangNmSoapService>, ServiceReference1.IPromotionsQuangNmSoapService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PromotionsQuangNmSoapServiceClient() : 
                base(PromotionsQuangNmSoapServiceClient.GetDefaultBinding(), PromotionsQuangNmSoapServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPromotionsQuangNmSoapService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PromotionsQuangNmSoapServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(PromotionsQuangNmSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), PromotionsQuangNmSoapServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PromotionsQuangNmSoapServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PromotionsQuangNmSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PromotionsQuangNmSoapServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PromotionsQuangNmSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PromotionsQuangNmSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.PromotionsQuangNm[]> GetAllAsync()
        {
            return base.Channel.GetAllAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.PromotionsQuangNm> GetByIdAsync(int id)
        {
            return base.Channel.GetByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<int> CreateAsync(ServiceReference1.PromotionsQuangNm promotion)
        {
            return base.Channel.CreateAsync(promotion);
        }
        
        public System.Threading.Tasks.Task<int> UpdateAsync(ServiceReference1.PromotionsQuangNm promotion)
        {
            return base.Channel.UpdateAsync(promotion);
        }
        
        public System.Threading.Tasks.Task<int> DeleteAsync(int id)
        {
            return base.Channel.DeleteAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPromotionsQuangNmSoapService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPromotionsQuangNmSoapService))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7282/PromotionsQuangNmSoapService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PromotionsQuangNmSoapServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPromotionsQuangNmSoapService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PromotionsQuangNmSoapServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPromotionsQuangNmSoapService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IPromotionsQuangNmSoapService,
        }
    }
}
