//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference2
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PromotionUsageQuangNm", Namespace="http://schemas.datacontract.org/2004/07/ElectricVehicleM.SoapService.QuangNM.Soap" +
        "Models")]
    public partial class PromotionUsageQuangNm : object
    {
        
        private string CustomerNameField;
        
        private System.Nullable<bool> IsValidField;
        
        private ServiceReference2.PromotionsQuangNm[] PromotionsQuangNmsField;
        
        private int UsageQuangNmidField;
        
        private System.Nullable<System.DateTime> UsedDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName
        {
            get
            {
                return this.CustomerNameField;
            }
            set
            {
                this.CustomerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsValid
        {
            get
            {
                return this.IsValidField;
            }
            set
            {
                this.IsValidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.PromotionsQuangNm[] PromotionsQuangNms
        {
            get
            {
                return this.PromotionsQuangNmsField;
            }
            set
            {
                this.PromotionsQuangNmsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsageQuangNmid
        {
            get
            {
                return this.UsageQuangNmidField;
            }
            set
            {
                this.UsageQuangNmidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UsedDate
        {
            get
            {
                return this.UsedDateField;
            }
            set
            {
                this.UsedDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PromotionsQuangNm", Namespace="http://schemas.datacontract.org/2004/07/ElectricVehicleM.SoapService.QuangNM.Soap" +
        "Models")]
    public partial class PromotionsQuangNm : object
    {
        
        private string ApplicableModelField;
        
        private System.Nullable<System.DateTime> CreatedAtField;
        
        private string DescriptionField;
        
        private System.Nullable<decimal> DiscountRateField;
        
        private System.Nullable<System.DateTime> EndDateField;
        
        private System.Nullable<bool> IsActiveField;
        
        private System.Nullable<int> MaxUsageField;
        
        private int PromotionQuangNmidField;
        
        private System.Nullable<System.DateTime> StartDateField;
        
        private string TitleField;
        
        private ServiceReference2.PromotionUsageQuangNm UsageQuangNmField;
        
        private System.Nullable<int> UsageQuangNmidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicableModel
        {
            get
            {
                return this.ApplicableModelField;
            }
            set
            {
                this.ApplicableModelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DiscountRate
        {
            get
            {
                return this.DiscountRateField;
            }
            set
            {
                this.DiscountRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaxUsage
        {
            get
            {
                return this.MaxUsageField;
            }
            set
            {
                this.MaxUsageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PromotionQuangNmid
        {
            get
            {
                return this.PromotionQuangNmidField;
            }
            set
            {
                this.PromotionQuangNmidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference2.PromotionUsageQuangNm UsageQuangNm
        {
            get
            {
                return this.UsageQuangNmField;
            }
            set
            {
                this.UsageQuangNmField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UsageQuangNmid
        {
            get
            {
                return this.UsageQuangNmidField;
            }
            set
            {
                this.UsageQuangNmidField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IPromotionUsageQuangNmSoapService")]
    public interface IPromotionUsageQuangNmSoapService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionUsageQuangNmSoapService/GetAll", ReplyAction="http://tempuri.org/IPromotionUsageQuangNmSoapService/GetAllResponse")]
        System.Threading.Tasks.Task<ServiceReference2.PromotionUsageQuangNm[]> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IPromotionUsageQuangNmSoapServiceChannel : ServiceReference2.IPromotionUsageQuangNmSoapService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class PromotionUsageQuangNmSoapServiceClient : System.ServiceModel.ClientBase<ServiceReference2.IPromotionUsageQuangNmSoapService>, ServiceReference2.IPromotionUsageQuangNmSoapService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PromotionUsageQuangNmSoapServiceClient() : 
                base(PromotionUsageQuangNmSoapServiceClient.GetDefaultBinding(), PromotionUsageQuangNmSoapServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPromotionUsageQuangNmSoapService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PromotionUsageQuangNmSoapServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(PromotionUsageQuangNmSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), PromotionUsageQuangNmSoapServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PromotionUsageQuangNmSoapServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PromotionUsageQuangNmSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PromotionUsageQuangNmSoapServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PromotionUsageQuangNmSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PromotionUsageQuangNmSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.PromotionUsageQuangNm[]> GetAllAsync()
        {
            return base.Channel.GetAllAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPromotionUsageQuangNmSoapService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPromotionUsageQuangNmSoapService))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7282/PromotionUsageQuangNmSoapService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PromotionUsageQuangNmSoapServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPromotionUsageQuangNmSoapService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PromotionUsageQuangNmSoapServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPromotionUsageQuangNmSoapService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IPromotionUsageQuangNmSoapService,
        }
    }
}
