// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace ElectricVehicleM.SoapService.QuangNM.SoapModels;

[DataContract]
public partial class PromotionUsageQuangNm
{
    [DataMember]
    public int UsageQuangNmid { get; set; }
    [DataMember]
    public string CustomerName { get; set; }
    [DataMember]
    public DateTime? UsedDate { get; set; }
    [DataMember]
    public bool? IsValid { get; set; }
    [DataMember]
    public virtual ICollection<PromotionsQuangNm> PromotionsQuangNms { get; set; } = new List<PromotionsQuangNm>();
}