// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace ElectricVehicleM.SoapService.QuangNM.SoapModels;


[DataContract]
public partial class PromotionsQuangNm
{
    [DataMember]
    public int PromotionQuangNmid { get; set; }
    [DataMember]
    public string Title { get; set; }
    [DataMember]
    public string Description { get; set; }
    [DataMember]
    public decimal? DiscountRate { get; set; }
    [DataMember]
    public DateTime? StartDate { get; set; }
    [DataMember]
    public DateTime? EndDate { get; set; }
    [DataMember]
    public bool? IsActive { get; set; }
    [DataMember]
    public string ApplicableModel { get; set; }
    [DataMember]
    public int? MaxUsage { get; set; }
    [DataMember]
    public DateTime? CreatedAt { get; set; }
    [DataMember]
    public int? UsageQuangNmid { get; set; }
    [DataMember]
    public virtual PromotionUsageQuangNm UsageQuangNm { get; set; }
}